name: PR Checks
on:
  pull_request:

jobs:
  test:
    name: Test changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git fetch origin main && git branch -l && git diff origin/main...HEAD
      - uses: pnpm/action-setup@v2
        name: Install PNPM
        with:
          version: 8
      - uses: actions/cache@v3
        name: Setup PNPM cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os}}-pnpm-store
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: pnpm i --frozen-lockfile
      - run: pnpm test:changed
  format:
    name: Format checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        name: Install PNPM
        with:
          version: 8
      - uses: actions/cache@v3
        name: Setup PNPM cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os}}-pnpm-store
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: pnpm i --frozen-lockfile
      - run: pnpm prettier:check
  linter:
    name: Lint checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        name: Install PNPM
        with:
          version: 8
      - uses: actions/cache@v3
        name: Setup PNPM cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os}}-pnpm-store
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: pnpm i --frozen-lockfile
      - run: pnpm build
      - run: pnpm lint